### ISSUE TITLE
Скрипты в HEAD?

### ISSUE THREAD

**Issue by fxc-dev** [VladERP/prototype#4]
**Вопрос:** в связи с чем было принято решение о [переносе подключения скриптов в HEAD](https://github.com/VladERP/prototype/commit/bb003f4d06c8ebfa0fd2088c54f976540ed06458#diff-b9707fe88797285e93483456d1389b61R12)? Это представляется антипаттерном, бьющим по производительности.  :confused:

**Comment by VladERP** [comment]
summernote(текстовый редактор) отваливается если подключать в любом другом месте. Если перенести bootstrap - отваливаются стили у summernote
